server:
  port: 80
  servlet:
    context-path: /chapter02
    session:
      timeout: 1s
  tomcat:
    uri-encoding: utf-8

#my:
#  name: wzq
#  address: China
#  favorites:
#    - 足球
#    - 徒步
#    - Coding

my:
  users:
    - name: 江南一点雨
      address: China
      favorites:
        - 足球
        - 徒步
        - Coding
    - name: sang
      address: GZ
      favorites:
        - 阅读
        - 吉他
